---
title: ""
# author: Qianqian Du, Taro Mieno, David S.Bullock
abstract: ""
output:
  bookdown::word_document2:
    # reference_docx: word-style.docx
    pandoc_args: ["-Fpandoc-crossref"]
bibliography: N_residual.bib
header-includes:
  - "\\usepackage{amsmath}"
# citation_package: natbib
# csl: "elsevier-harvard.csl"
---

```{r echo = F, results='hide', message = F}
library(knitr)
library(here)
?rmarkdown::pandoc_available
# === set wd ===#
# Notes: not really necessary to set the working directory as long as this Rmd file is part of an R project and the evaluation directory is set to "Project".

opts_knit$set(root.dir = here())

options(htmltools.dir.version = FALSE)
options(knitr.duplicate.label = "allow")

opts_chunk$set(
  fig.align = "center", 
  fig.retina = 5,
  warning = F, 
  message = F,
  cache = F,
  echo = F,
  comment = '', 
  fig.width = 6, 
  fig.height = 6
  )

```

# Introduction

 + There have been studies showing that residual N in soil may affect the next year's EONR.
 + OFPE is a useful way providing information for agricultrual practices, and it is getting more popular.
 + No studies have explored the impact of OFPE on fields, other than providing fields information and finding EOIRs
 + We used APSIM and found that running OFPE can create field heterogenouity, which can increase the vatiation of EONRs for the next year due to different N applications in each site and then result in different residual N in soil. 
    + This is more relavent to corn-corn rotation
    + For corn-soy rotation, the field heterogenouity still exsits, but it is way smaller than corn-corn
    + The degree/range of field heterogenouity caused by residual N varys by precipitation.
+ Implication: 
  + Corn-soy rotation can mitigate field heterogenouity due to OFPE
  + Do not use consistent trial design over years
  + How much N applied this year will affect the yield response in the next year, they are continous events. Future studies can work on finding EONR considering multiple years? 


# Material and Methods

+ APSIM's general info in a few sentences with citations
+ APSIM prameters setup for simulations
  + soil
  + crop
  + weather
  + mangement
+ Trial design 
  + random trial design over years
  + same trial design over years
  + corn-corn rotation 
  + corn-soy rotation
+ Simulate true yield response functions and estimate the 3 kinds of EONR


# Results

+ True yield response functions under 4 scenarios
+ Estimated EONRs and compare them
+ optimal- under wet years vs dry years.


# Conclusion 






# References {-}

<div id="refs"></div>

















