---
title: "Spatial and Temporal Heterogeneity in Soil N Caused by On-Farm Precision Experimentation"
# author: Qianqian Du, Taro Mieno, David S. Bullock
abstract: ""
output:
  bookdown::word_document2:
    # reference_docx: word-style.docx
    pandoc_args: ["-Fpandoc-crossref"]
bibliography: N_residual.bib
header-includes:
  - "\\usepackage{amsmath}"
# citation_package: natbib
# csl: "elsevier-harvard.csl"
---

```{r echo = F, results='hide', message = F}
library(knitr)
library(here)
?rmarkdown::pandoc_available
# === set wd ===#
# Notes: not really necessary to set the working directory as long as this Rmd file is part of an R project and the evaluation directory is set to "Project".

opts_knit$set(root.dir = here())

options(htmltools.dir.version = FALSE)
options(knitr.duplicate.label = "allow")

opts_chunk$set(
  fig.align = "center", 
  fig.retina = 5,
  warning = F, 
  message = F,
  cache = F,
  echo = F,
  comment = '', 
  fig.width = 6, 
  fig.height = 6
  )

```


# Abstract 

On-farm precision experiments (OFPE) have become valuable tools for determining nitrogen (N) rates that increase economic profits while potentially reduce environmental impacts. However, despite the insights gained from OFPE, no studies have examined the impact of applying variable N rates on soil residual N in fields where these experiments were conducted. We suspect that applying variable N rates may lead to differing levels of residual soil N, which could, in turn, influence the following year’s yield response to N and affect the optimal N rate for that site. This could potentially bias the yield response estimation when using OFPE data. This study uses the Agricultural Production Systems sIMulator (APSIM) to simulate the process of applying variable N on a hypothetical field with corn-corn and corn-soybean rotations, using a completely randomized trial design of N across years and a consistent trial design of N, respectively. Results show that soil N heterogeneity, caused by variable N application, is most pronounced in continuous corn rotations with a consistent trial design each year. In contrast, fields with corn-soybean rotations exhibit less soil N heterogeneity, likely because soybeans, as legumes, play a vital role in enriching and balancing soil nitrogen levels through biological nitrogen fixation when grown between two years of corn. The presence of soil N heterogeneity increases the variability in site-specific economically optimal N rate (EONR), thereby increasing the profit difference between site-specific and field-uniform EONR. Consequently, the EONR estimated from observed OFPE data may differ from the true field-uniform EONR. However, in the corn-soybean rotation system, we find no significant difference between the true uniform EONR and the OFPE-estimated EONR. 


# Introduction

As optimal input rates usually vary across and within fields, precision agriculture (PA) technology has been increasingly adopted by farmers [@mcfadden2023precision]. On-farm precision experimentation (OFPE), where researchers and farmers collaborate using PA tools to collect data, started in the late 1990s and has also been increasingly conducted to provide valuable information for field characteristics and profitability at specific fields [@cook1998precision; @bullock2002adding; @pringle2004field; @panten2010enhancing; @paccioretti2021statistical; @hegedus2023towards]. OFPE typically relies on variable rate applicators (VRA) to apply different input rates based on a field trial design, allowing for the estimation of the relationship between inputs and yield. The data and insights gained from OFPE have shown potential for identifying optimal input rates that enhance economic returns while potentially reducing environmental impacts [@bullock2019data]. However, despite these benefits, no studies have examined the impact of applying variable nitrogen rates on residual soil nitrogen in fields where these experiments were conducted.

Previous work have provided evidence that fertilization in the previous year can consistently increase yields, grain N, and residue N in second-year crops across multiple locations and years [@hooker1983effects; @bundy1988effect; @maaz2017residual]. Studies have documented that high levels of residual soil N may lead to nitrate accumulation, reduce the yield response of subsequent crops, or result in leaching beyond the rooting zoon [@halvorson1994nitrogen; @halvorson2005corn; @kelley2013nitrate]. Empirical researches have consistently shown that residual soil N levels are significantly affected by N fertilizer applications and vary with changes in application rates [@hong2007economically; @ferguson2002site; @alotaibi2018economic; @belanger2003residual; @jokela1989corn]. @roth1990soil showed that soil residual N not only varies after the harvest of corn fertilized at different N rates but can also accumulate and be present in substantial amounts in the spring, indicating the need to consider residual soil N in N management. However, except the preplant soil nitrate test (PPNT) tool [@magdoff1984soil; @bundy1995soil; @schroder2000does], current N recommendation tools rarely account for the residual soil N from previous fertilizer applications when calculating economically optimal rates. Therefore, we hypothesis that applying variable nitrogen rates during the OFPE process may result in differing levels of residual soil nitrogen within the field, which could, in turn, influence the following year’s yield response to applied nitrogen and affect the optimal rate for that site. This variation could potentially bias yield response estimations and the recommendations for economically optimal nitrogen rates (EONR) when using OFPE data. The main objective of this study is to examine the spatial and temporal heterogeneity in soil nitrogen caused by OFPE itself and its impact on economic evaluations. 

We use the Agricultural Production Systems sIMulator (APSIM) to simulate variable N application on a hypothetical field under 24 distinct scenarios. These scenarios were constructed by varying four key factors: crop rotation (corn-corn and corn-soybean), weather conditions (dry, normal, and wet years), N trial design types (consistent rates across years and randomized rates across year), and tillage management strategies (with tillage and no tillage). This simulation framework enables us to evaluate how OFPE may influence yield response functions shaped by residual nitrogen dynamics under diverse agronomic and environmental conditions. 

Results show that soil inorganic N heterogeneity, caused by variable N application, did led to variation in yield response and EONRs. This effect was most pronounced in continuous corn rotations with a consistent trial design each year, followed by the continuous corn rotation field with randomized trial design. In contrast, fields with corn-soybean rotations exhibited less residual soil N heterogeneity, likely because soybeans, as legumes, help enrich and balance soil nitrogen levels through biological nitrogen fixation when grown between two corn seasons. Additionally, rainfall plays a crucial role in reducing the field-evel hetergenouity caused by residual inorganic N. With soybean grown between two years of corn production, there is a one-and-a-half-year period during which rainfall occurs without additional nitrogen application. During this time, the field is more likely to receive sufficient rainfall to leach away residual nitrogen remaining from the previous corn season.

Based on the simulation results, the presence of residual soil N heterogeneity increases the variability in site-specific economically optimal N rate (EONR), thereby increasing the profit difference between site-specific and field-uniform EONR. Consequently, the EONR estimated from observed OFPE data may differ from the true field-uniform EONR. However, in the corn-soybean rotation system, we find no significant difference between the true uniform EONR and the OFPE-estimated EONR. 

These findings are important, as no studies have previously pointed out the issue that, beyond the valuable information gained from OFPE, running OFPE itself can introduce spatial and temporal heterogeneity in soil N. This may complicate yield response and EONR estimations in subsequent growing seasons and could have long-term effects on fields where OFPE has been conducted. Growing soybeans between two years of corn production can help mitigate the heterogeneity mentioned above. This potential benefit of practicing a corn-soybean rotation has not been discussed in the previous literature and could provide valuable information to farmers when deciding between continuous corn planting and corn-soybean rotations. Furthermore, this study provides insights into the potential long-term effects of repeatedly conducting OFPE on the same field. For example, it may be advisable to avoid using the same trial design map over multiple years. Future studies are needed to explore methods for determining EONR that account for nitrogen residual dynamics over multiple years.

# Conceptual Framework

Residual N in soil can affect the slope of yield response curve. For example, in a field with high residual N, applying 150 or 200 lb/ac N may result in little difference in yield, leading to a relatively flat yield response curve. In contrast, in a field with low residual N, applying 150 or 200 lb/ac N can significantly impact yield, resulting in a steeper yield response curve. We hypothesize that applying variable rates of N can lead to different amounts of residual N for the following growing season, which way increase the variation in the EONR for the field. Figure \@ref(fig:underlying-assumption) illustrates this conceptually. 

$N_s$ represents the residual N in the soil from the N application in the previous growing season. $N_p$ represents the N available to the crop through mineralization, organic matter decomposition, and other natural soil processes that release plant-accessible N. When analyzing observed N and yield data from OFPEs, we can generate figures similar to the top left panel of Figure \@ref(fig:underlying-assumption). This figure illustrates the EONR derived from OFPE data, denoted as $N^*$, indicating total N needed by the crop to maximize profit. However, in most farmer-centered on-farm experiments, N application rates are designed around the farmers’ existing management decisions rather than including a zero-N application treatment. As a result, it is common for OFPEs to lack observations where no nitrogen was applied. Additionally, $N_s + N_p$ varies significantly based on soil characteristics, weather conditions, and other environmental factors, without extensive soil testing, pinpointing the location of $N_s + N_p$ on the x-axis is difficult. This uncertainty complicates the estimation of the economically optimal applied nitrogen rate ($N_A^*$), which is calculated as $N_A^* = N^* - (N_S+N_P)$. 

In the Corn Belt, for example central Illinois, fields are generally flat and relatively homogeneous, meaning that different locations within a field are likely to exhibit similar yield responses. This aligns with evidence from previous studies that the profit from applying a uniform optimal nitrogen rate is comparable to the profit from implementing site-specific optimal N rates [add citations]. However, conducting OFPE and applying variable N rates can result in different residual N levels ($N_s$) in the soil for the following growing season. These variations influence the yield level when no N is applied, ultimately altering the yield response functions (right panel of Figure \@ref(fig:cc-ofpe-consistent)). As a result, the observed yield response in subsequent seasons may differ from initial expectations, introducing additional complexity in estimating the economically optimal application N rate.


# Material and Methods

To examine how variable N application through OFPE impacts the yield response to N in following growing seasons, this study utilizes a crop simulation model to generate simulated yield responses to N across different OFPE scenarios. Economic evaluations are then calculated based on the simulated yields and applied N rates. 

## The APSIM Modeling Platform and Crop Models

The Agricultural Production Systems sIMulator (APSIM) is an open-source, advanced agricultural systems simulator that integrates various process-based models within a modular framework [@holzworth2014apsim; @keating2003overview]. Further details on APSIM and its performance across various studies are available at http://www.apsim.info. The crop models in APSIM simulate crop growth by capturing a comprehensive set of physiological processes, including phenology, organ development, and water and nutrient uptake, among others. These processes operate on a daily time step and respond to environmental conditions and management practices. By accounting for a broad spectrum of growth factors, APSIM provides an accurate and dynamic view of how crops interact with their environment, allowing us to examine how applied fertilizer nitrogen may influence residual soil nitrogen accumulation in the spring and, consequently, affect yield response later in the growing season [@keating2003overview; @holzworth2014apsim].

The crop models used in this study include corn [@carberry1991tailoring] and soybean [@robertson1998simulating] crop models. The SOILN module [@probert1998apsim] in APSIM was used to model soil N and C cycling, as well as to simulate nitrogen mineralization from soil organic matter, thereby generating the nitrogen supply available to a crop from the soil. Clarion loam soil was used as the soil type in the simulated field, soil profile information can be obtained from https://websoilsurvey.sc.egov.usda.gov/App/HomePage.htm. Simulations were performed in a stylized representative field at a rainfed location in the US Midwest in Ames, IL. 


## Crop Growing Simulation set up

The simulation process was consecutive to account for carry-over soil N effects for seven years without annual re-initialization between each growing season. The following crop management prameters were held constant across years for each crop type. Planting depth was 50 mm for both corn and soybean. Plant polulation was 8 and 30 plants $m^{-2}$ for corn and soysean, respectively. Crops were planted on April 22nd and harvest on October 16th each year. Row spacing was 760 mm for both corn and soybean. Nitrogen fertilizer was applied near planting on May 5th and was only applied to corn. Tillage was applied on October 18th each year in the fall after the crop was harvested and on April 16th in the spring before the crop was planted.

## Simulation Scenarios 

Since the aim of this study is to examine the impact of variable rate N application on soil N residuals and its effect on yield response, only N application rates will be considered as a variable in the OFPE trials, with corn and soybean seeding rates kept consistent across fields and years.

Two cropping systems were compared in this study: continuous corn (CC) rotation and corn-soybean (CS) rotation. Two types of trial designs were used for the simulations: a completely randomized trial design and a consistent trial design over multiple years. Each simulated N-OFPE trial included of six targeted N rates: 0, 50, 150, 200, 250, and 300 kg/ha. Figure @\ref illustrates the trial design maps. In the consistent trial design scenario, plots receiving higher N rates continue to receive the same high rates each year, leading to greater residual inorganic N accumulation over time. As a result, a wider range of yield response variations is expected in OFPEs following the consistent trial design. In contrast, in the randomized trial design scenario, N application rates are reassigned randomly each year. This reduces the likelihood of N accumulation or depletion at specific locations, decreasing long-term N imbalances across the field.

Weather could influence the yield response to N and soil N level grately. To isolate weather effects and make applied N level as the only variable in the simulation. We used actual daily weather data obtained from Daymet [@daymet] and replicated it nine times, creating a 10-year simulation under same weather conditions each year. This approach ensures that any variance in yearly yield response is solely due to differences in residual N resulting from variable N applications. To examine the impact of weather on how residual inorganic N in the soil affects corn yield responses, two different weather scenarios were created using data from a normal year (2019) and a wet year (2010). Figure @ref(fig:cs-consis-leaching) demonstrated the weather conditions. 

Tillage strategies can significantly influence soil N dynamics by affecting soil structure, organic matter decomposition, and N mineralization. Both tillage and no-tillage scenarios were included in the simulations to assess the impact of residual inorganic N in the soil on corn yield responses.


Overall, this study considered two cropping rotation systems, two trial design types, two tillage strategies, and two weather conditions, resulting in a total of 16 scenarios.


## EONR Estimations
By taking advantage of APSIM’s capability to model crop yield at any desired N rate increment, we used the APSIM model to simulate corn yield at 5 kg/ha increments from 0 to 270 kg/ha of N. This enabled us to calculate profit (crop yield multiplied by crop price minus N rate multiplied by N price) for each N rate. The EONR corresponds to the N rate that provides the highest profit, representing the true EONR at each site. In each croping system with a trial design, we compared the true site-spcific EONR and the true optimal uniform EONR using simulated yield response data gennerated by APSIM, as well as the estimated uniform EONR using observed OFPE data gennerated from APSIM. 

$$
EONR_{i}^{VR} = \underset{N_i}{\text{Argmax}} \ \{\text{yield}_i (N_i) * p_c \ - \ N_i * p_{n} \}, \quad \text{for } i = 1, 2, 3, \ldots, 200.
$$

$$
EONR^{UR} = \underset{N}{\text{Argmax}} \ \{ \sum_{i=1}^{200} yield_i (N) * p_c \ - N*p_{n} \}
$$

Where $yield_i$ is the yield level in site $i$ generated by APSIM simulations given by the applied N level. $p_c$ and $p_n$ represents corn price and N price, respectively. 

As mentioned above, true yield responses are not observed in reality, as we can only observe one yield level from each site. With the observed OFPE data, we estimate the field yield response using a Generalized Additive Model (GAM) [@hastie2017generalized], specified as Equation (3), where $s(N)$ is a smooth function of N rates in OFPE, and $u$ is the random error term. In stead of assuming strict parametric formulas, the GAM approach allows for flexible modeling of the relationship between yield and N by using data-driven functions [@gardner2021economic]. This flexibility is particularly useful for capturing complex yield response curves that may not be well-represented by traditional linear or polynomial models. We then estimate the uniform EONR based on the estimated yield response, denoted as $\widehat{EONR^{UR}}$. Estimation process is listed below.

$$
yield = s(N) + u,
$$

$$
\widehat{EONR^{UR}} = \underset{N}{\text{Argmax}} \  [\widehat{yield(N)} * p_c \ - \ N*P_n] 
$$

# Results

## True yield response functions

The simulated yield responses for CC rotation are shown in Figure \@ref(fig:cc-ofpe-consistent) under two trial designs: a completely randomized trial design (left panel) and a consistent trial design (right panel). The intersections on the y-axis of the yield response curves visually represent the field heterogeneity in residual inorganic soil nitrogen resulting from variable nitrogen applications in previous growing seasons. The results indicate that after nine years of continuous corn production, substantial heterogeneity developed in the field due to variable N applications, as reflected in the site-specific yield response functions. This finding aligns with our hypothesis. Fields with a consistent trial design exhibited greater heterogeneity in yield responses. As expected, sites that consistently received higher nitrogen rates accumulated more residual inorganic soil nitrogen over time. This pattern is evident in the figure: after nine years, sites that had repeatedly received the highest nitrogen rates (300 kg/ha) were able to produce approximately 220 bu/ac in the tenth year of OFPE without additional nitrogen application, whereas sites that had received the lowest rates (0 kg/ha) yielded only about 26 bu/ac. On the other hand, fields under a completely randomized trial design exhibited less heterogeneity in residual inorganic nitrogen over time. Since each site received varying nitrogen rates across years, the likelihood of consistent nitrogen accumulation at specific locations was reduced.

In the CS rotation system, the simulated yield responses exhibited significantly less field heterogeneity compared to CC, as shown in Figure @ref(fig:cs-ofpe-consistent). The difference in yield between plots receiving 300 kg/ha and 0 kg/ha of N was only about 25 bu/ac. This is likely because, when soybeans are grown between two years of corn, they play a significant role in enriching and balancing soil N levels through biological N fixation. Additionally, since farmers do not apply N fertilizer to soybean trials, there is a period of one and a half years without N application in the CS rotation. This period likely receives sufficient rainfall to wash away N residuals, resulting in minimal N accumulation differences among sites and reducing the impact of residual N on yield responses.


## EONR estimations

Table 1 shows the true site-specific, true uniform, and estimated EONR for cc and cs rotations under both consistent and completely randomized trial designs. Results indicate that field heterogeneity, caused by different amount of residual inorganic N in the soil due to different N application rates, leads to differences in yield responses and, consequently, variations in site-specific EONRs. 

As expected, the cc rotation with a consistent trial design exhibits the widest range of site-specific EONRs. In this scenario, some areas require as little as 44.6 lb/ac of N to reach the EONR due to the accumulation of inorganic N in the soil from years of consistently high N application. The difference between the true uniform EONR and the estimated EONR from observed OFPE data indicates that the field heterogeneity mentioned above can potentially introduce bias in EONR estimations. This bias can further result in significant profit differences when applying site-specific EONR, uniform EONR, or estimated EONR from OPFE data. In contrast, the cs rotation exhibits much lower field heterogeneity caused by variable N applications, leading to a closer alignment between the estimated EONR from observed OFPE data and the true uniform EONR derived from APSIM simulations. Furthermore, there is less difference between applying a uniform optimal EONR and a site-specific EONR in cs fields.


## N leaching

Figure @ref(fig:cc-consis-leaching) shows the annual N leaching in a cc rotation field results from APSIM simulations. The results show that applying 250 kg/ha of N annually can result in approximately 50 kg/ha of N leaching. Meanwhile, continuously applying 300 kg/ha of N leads to about 87 kg/ha of N leaching, which is seven times higher than the leaching observed when N is applied at rates below 200 kg/ha per year. These findings indicate that consistently applying high N rates to the same location significantly increases N leaching, which may potentially reduce N use efficiency, degrade soil health, and contaminate water sources. 

Figure @ref(fig:cs-consis-leaching) shows the annual N leaching results from APSIM simulations for a CS rotation field. Similar to the cc field, excessive N application over time leads to increased N leaching. However, N leaching in the CS rotation is significantly lower. Applying 300 kg/ha of N results in approximately 35 kg/ha of leaching— less than half of the leaching results from the CC rotation.

### in ofpe settings, look at the distribution of N leaching at diff N rates


## Different weather situations

Weather plays a critical role in influencing the magnitude of field heterogeneity caused by variable N application, particularly through its effects on precipitation. In this study, historical weather data from 1993 to 2021 were used to examine how rainfall affects the accumulation and distribution of residual inorganic N in the soil, and in turn, alters crop yield responses (Figure @ref() and Figure @ref()). Figure @ref() illustrates the annual precipitation levels from 1993 to 2021. The results suggest that higher precipitation levels tend to reduce the spatial variability of residual N by promoting greater leaching and redistribution of nutrients throughout the soil profile. In contrast, during dry years, reduced rainfall limits N leaching, allowing more residual inorganic N to remain in the soil—particularly in areas that received higher N rates. This leads to greater accumulation of residual N and more pronounced differences in yield responses across the field, thereby increasing overall field heterogeneity.

Similar precipitation effects were observed in fields under the corn–soybean (CS) rotation (Figure @ref()). In dry years, limited rainfall reduced the leaching of residual inorganic N, allowing for greater retention of nitrogen in the soil, particularly in areas that previously received higher N rates. This led to increased variation in yield responses across the field. Conversely, in wet years, higher precipitation facilitated more uniform leaching and redistribution of residual N, resulting in a more even nutrient profile and subsequently less variation in yield responses. These findings indicate that, even in a CS rotation where nitrogen is not applied during the soybean year, weather, especially rainfall, continues to play a key role in shaping the spatial patterns of residual N and yield variability.


## Without tillage situations

Figure @ref() shows the yield responses with and without tillage under a corn–corn rotation and a consistent trial design for nitrogen (N) management. Based on the simulation results, the yield responses exhibit greater variation in the tilled field, suggesting that tillage increased the heterogeneity caused by variable N application. One possible explanation is that higher N application results in higher yields, which in turn produce more crop residue after harvest. Tillage plays an important role in mixing and incorporating residues into the soil. As a result, areas with greater residue may experience higher levels of organic matter and increased microbial activity following tillage, leading to greater heterogeneity across the field.

However, no significant tillage effect was observed under the same simulation setup when a corn–soybean rotation was implemented (Figure @ref()). A possible explanation could be since soybeans do not require N fertilizer and generally produce lower biomass than corn, the amount of residue left after soybean harvest was considerably lower. Moreover, the year between corn crops allowed time for natural processes, particularly rainfall, to leach or redistribute much of the residual inorganic N left from the previous corn season. As a result, the level of residual N was already reduced and more evenly distributed across the field by the time corn was planted again. Consequently, the presence or absence of tillage did not significantly affect the spatial variability or heterogeneity of yield response in the CS rotation.


# Discussion


This study provides insights into the potential long-term effects of repeatedly conducting OFPE on the same field. Consistently applying variable N rates in the same location can lead to uneven inorganic N soil residual accumulation, which in turn influences yield response functions and EONR estimations in the following year. In addition, excessive N buildup in some areas and depletion in others could reduce N use efficiency and increase the risk of environmental impacts such as leaching and greenhouse gas emissions. Therefore, it may be advisable to avoid using the same trial design map over multiple years, especially in a continuous corn field. 

Future research is needed to explore methods for determining EONR that incorporate inorganic N soil residual dynamics over multiple years. Since N carryover can significantly affect yield response, developing models that integrate historical N application data, soil N mineralization rates, and environmental factors will be important for refining N management strategies. 

Soil physical characteristics can significantly influence N dynamics and impact the outcomes observed in this study. For example, soil texture affects water retention, drainage, and N leaching rates, which in turn influence the accumulation of residual inorganic N and its availability for crops- sandy soils with high permeability may result greater N leaching, reducing the carryover of residual N and potentially increasing the EONR. Clay or silt loam have higher water-holding capacity, which can slow N leaching and lead to greater residual N accumulation over time.


# Conclusion 


This study evaluated how variable rate N applications may affect yield responses, EONR estimations, and N leaching across 24 scenarios defined by crop rotation, weather, trial design, and tillage. Results show that in continuous corn (CC) systems with consistent trial designs, repeated application of N in the same locations leads to significant residual N accumulation, increasing field heterogeneity and causing wide variation in yield response and site-specific EONRs. In contrast, corn–soybean (CS) rotations and randomized trial designs reduce this heterogeneity due to biological N fixation, lower residue, and natural leaching during the soybean year.

Weather plays a critical role, with dry years amplifying variability in residual N and yield response, while wet years reduce it. Tillage further increases heterogeneity in CC systems by enhancing residue incorporation, but has minimal effect in CS systems. These findings suggest that using consistent trial designs over time, especially in CC fields, can introduce bias in EONR estimates and reduce nitrogen use efficiency. Future research should integrate residual N dynamics and weather variability into models to improve long-term nitrogen management.


# References {-}

<div id="refs"></div>

















