---
title: "EONR_evaluations"
author: "Qianqian Du"
date: "2024-10-17"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(data.table)
library(gam)
library(here)
```

# Eonomic analysis for corn-corn consistent setting

```{r cache=TRUE}
###---- upload the simulation result ----###
cc_consisten_b105 <- readRDS(here::here("Data", "Processed-Data", "cc_consistent_B105.rds"))


###---- find the simulated true yield response curves ----###

cc_consisten_b105_yield <- cc_consisten_b105 %>% 
  mutate(CropYield = CropYield*10*0.0159/0.85) %>% # change from g/m^2 to bu/ac
  mutate(applied_N = applied_N*0.8921) %>% # change from kg/ha to lb/ac
  data.table() %>% 
  .[year == 2023, ] %>% 
  .[, .(yield_max = max(CropYield)), by = .(applied_N, plot_id)] 


###---- create N seq for trial designs ----###
N_rates <- data.frame(
    var_N = c(0, 50, 100, 150, 200, 250, 300)
  )%>% 
  mutate(var_N = as.character(var_N*0.8921))

number_plot <- 100

set.seed(230829)

###--- trial design ---###
applied_N <- data.frame(
  year_1 = sample(N_rates$var_N, number_plot, replace = TRUE),
  year_2 = sample(N_rates$var_N, number_plot, replace = TRUE),
  year_3 = sample(N_rates$var_N, number_plot, replace = TRUE),
  year_4 = sample(N_rates$var_N, number_plot, replace = TRUE),
  year_5 = sample(N_rates$var_N, number_plot, replace = TRUE),
  year_6 = sample(N_rates$var_N, number_plot, replace = TRUE),
  year_7 = sample(N_rates$var_N, number_plot, replace = TRUE),
  year_8 = sample(N_rates$var_N, number_plot, replace = TRUE),
  year_9 = sample(N_rates$var_N, number_plot, replace = TRUE),
  plot_id = seq(1, 100, by = 1)) %>% 
  as.list()


cc_consistant_td <- data.frame(
  applied_N = as.numeric(applied_N$year_9[1:100]),
  plot_id = as.character(seq(1,100, by = 1))
) %>% 
  left_join(., cc_consisten_b105_yield, by = c("applied_N", "plot_id"))


###---- Visualize the true yield responses and the estimated yield response from ofpe  ----###
ggplot()+
  geom_point(aes(x = applied_N, y = yield_max, color = plot_id), data = cc_consisten_b105_yield, size = 0.5)+
  geom_line(aes(x = applied_N, y = yield_max, color = plot_id), data = cc_consisten_b105_yield, size = 0.5)+
  # geom_point(aes(x = applied_N, y = yield_max, color = plot_id), data = cc_consistant_td, color = "blue")+
  # geom_smooth(aes(x = applied_N, y = yield_max), data = cc_consistant_td, color = "blue")+
  scale_color_manual(
    name = "N level",  # Change legend title
    values = c("red", "orange", "green", "blue", "cyan", "purple", "pink"), # Adjust colors if needed
    labels = c("0", "50", "100", "150", "200", "250", "300")  # Change labels
  )+
  ylab("Yield (bu/ac)")+
  xlab("Applied N")+
  theme_bw()

```


```{r cache=TRUE}
###---- Find the site-specific EONR  ----###

#--- set prices ---#
corn_price <- 4 
N_price <- 0.5


cc_consist_yield_analysis <- cc_consisten_b105_yield %>% 
  rowwise() %>% 
  data.table() %>% 
  .[, profit := yield_max*corn_price - applied_N*N_price] %>% 
  group_by(plot_id) %>%
  filter(profit == max(profit))


ggplot()+
  geom_point(aes(x = applied_N, y = yield_max, color = plot_id), data = cc_consisten_b105_yield, size = 0.5)+
  geom_line(aes(x = applied_N, y = yield_max, color = plot_id), data = cc_consisten_b105_yield, size = 0.5)+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cc_consistant_td, color = "blue")+
  geom_smooth(aes(x = applied_N, y = yield_max), data = cc_consistant_td, color = "blue")+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cc_consist_yield_analysis, color = "red")+
  xlab("N rate")+
  ylab("Yield")+
  ggtitle("yield response to N with corn-corn consistent trial design")+
  theme_bw()

###--- make the figure to show that the levels change is the same as we expected ---###
# Convert plot_id to a factor and ensure levels are ordered numerically
cc_consisten_b105_yield$plot_id <- factor(cc_consisten_b105_yield$plot_id, 
                                          levels = as.character(1:10)) 

ggplot() +
  geom_point(aes(x = applied_N, y = yield_max, color = plot_id), 
             data = cc_consisten_b105_yield, size = 0.5) +
  geom_line(aes(x = applied_N, y = yield_max, color = plot_id), 
            data = cc_consisten_b105_yield, size = 0.5) +
  labs(color = "N level") +
  xlab("N rate") +
  ylab("Yield") +
  ggtitle("Yield response to N with corn-corn consistent trial design") +
  theme_bw()




# site-specific EONRs statistic #
summary(cc_consist_yield_analysis$applied_N)


# Uniform EONR #

cc_consist_uni <- cc_consisten_b105_yield %>% 
  rowwise() %>% 
  data.table() %>% 
  .[, profit := yield_max*corn_price - applied_N*N_price] %>% 
  #---- find each level of N can bring how much profit for the whole field ----#
  .[, .(yield = mean(yield_max), profit = mean(profit)), by = applied_N] %>% 
  #---- filter out the uniform N that brings the highest profit ----#
  .[profit == max(profit), ] %>% 
  .[, type := "uniform N rate"]

cc_consist_uni


## Estimate the EONR from OFPE ##

gam_re <- gam(
  yield_max
  ~ s(applied_N),
  data = cc_consistant_td
)


eval_data <- data.frame(
  applied_N = seq(
    0, 240, by = 5
  )
) %>% 
  data.table() %>% 
  .[, y_hat := predict(gam_re, newdata = ., se = TRUE)]

cc_consistant_estimate <- eval_data %>% 
  .[, profit := y_hat*corn_price - applied_N*N_price] %>% 
  filter(profit == max(profit)) %>% 
  .[, type := "ofpe estimated N rate"]
  
```

```{r cache=TRUE}
# Compare the 3 types of EONRs together for cc ofpe in previous years

# site-specific EONRs statistic #
summary(cc_consist_yield_analysis$applied_N)
summary(cc_consist_yield_analysis$profit)

# Uniform EONR #
cc_consist_uni

# Estimated EONR #
cc_consistant_estimate

```



# Eonomic analysis for corn-corn ofpe setting
```{r cache=TRUE}
###---- upload the simulation result ----###
cc_ofpe_b105 <- readRDS(here::here("Data", "Processed-Data", "cc_ofpe_B105_1_50.rds"))

###---- find the simulated true yield response curves ----###

cc_ofpe_b105_yield <- cc_ofpe_b105 %>% 
  mutate(CropYield = CropYield*10*0.0159/0.85) %>% 
  mutate(applied_N = applied_N*0.8921) %>% 
  mutate(applied_N = round(applied_N, digits = 2)) %>% 
  data.table() %>% 
  .[year == 2023, ] %>% 
  .[, .(yield_max = max(CropYield)), by = .(applied_N, plot_id)]


cc_ofpe_td <- data.frame(
  applied_N = round(as.numeric(applied_N$year_9[1:100])*0.8921, digit = 2),
  plot_id = as.character(seq(1,100, by = 1))
) %>% 
  left_join(., cc_ofpe_b105_yield, by = c("applied_N", "plot_id"))


###---- Visualize the true yield responses and the estimated yield response from ofpe  ----###
ggplot()+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cc_ofpe_b105_yield, size = 0.5)+
  geom_line(aes(x = applied_N, y = yield_max, group = plot_id), data = cc_ofpe_b105_yield, size = 0.5)+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cc_ofpe_td, color = "red")+
  geom_smooth(aes(x = applied_N, y = yield_max), data = cc_ofpe_td, color = "red")+
  xlab("N rate")+
  ylab("Yield")+
  ggtitle("yield response to N with corn-corn randomized trial design")+
  theme_bw()

```


```{r cache=TRUE}
###---- Find the site-specific EONR  ----###

#--- set prices ---#

cc_ofpe_yield_analysis <- cc_ofpe_b105_yield %>% 
  rowwise() %>% 
  data.table() %>% 
  .[, profit := yield_max*corn_price - applied_N*N_price] %>% 
  group_by(plot_id) %>%
  filter(profit == max(profit))



ggplot()+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cc_ofpe_b105_yield, size = 0.5)+
  geom_line(aes(x = applied_N, y = yield_max, group = plot_id), data = cc_ofpe_b105_yield, size = 0.5)+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cc_ofpe_td, color = "blue")+
  geom_smooth(aes(x = applied_N, y = yield_max), data = cc_ofpe_td, color = "blue")+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cc_ofpe_yield_analysis, color = "red")+
  theme_bw()

# site-specific EONRs statistic #
summary(cc_ofpe_yield_analysis$applied_N)

# Uniform EONR #

cc_ofpe_uni <- cc_ofpe_b105_yield %>% 
  rowwise() %>% 
  data.table() %>% 
  .[, profit := yield_max*corn_price - applied_N*N_price] %>% 
  #---- find each level of N can bring how much profit for the whole field ----#
  .[, .(yield = mean(yield_max), profit = mean(profit)), by = applied_N] %>% 
  #---- filter out the uniform N that brings the highest profit ----#
  .[profit == max(profit), ] %>% 
  .[, type := "uniform N rate"]

cc_ofpe_uni


## Estimate the EONR from OFPE ##

gam_re <- gam(
  yield_max
  ~ s(applied_N),
  data = cc_ofpe_td
)


eval_data <- data.frame(
  applied_N = seq(
    0, 240, by = 5
  )
) %>% 
  data.table() %>% 
  .[, y_hat := predict(gam_re, newdata = ., se = TRUE)]

cc_ofpe_estimate <- eval_data %>% 
  .[, profit := y_hat*corn_price - applied_N*N_price] %>% 
  filter(profit == max(profit)) %>% 
  .[, type := "ofpe estimated N rate"]
  
```

```{r cache=TRUE}
# Compare the 3 types of EONRs together for cc ofpe in previous years

# site-specific EONRs statistic #
summary(cc_ofpe_yield_analysis$applied_N)
summary(cc_ofpe_yield_analysis$profit)

# Uniform EONR #
cc_ofpe_uni

# Estimated EONR #
cc_ofpe_estimate

```


# Eonomic analysis for corn-soy consistent setting

```{r cache=TRUE}
###---- upload the simulation result ----###
cs_consistent_b105 <- readRDS(here::here("Data", "Processed-Data", "corn_soy_consistent_B105.rds"))

###---- find the simulated true yield response curves ----###

cs_consist_yield <- cs_consistent_b105 %>% 
  mutate(CropYieldMaize = CropYieldMaize*10*0.0159/0.85) %>% 
  mutate(applied_N = applied_N*0.8921) %>% 
  mutate(applied_N = round(applied_N, digits = 2)) %>% 
  data.table() %>% 
  .[year == 2023, .(yield_max = max(CropYieldMaize)), by = .(applied_N, plot_id)]


###---- create N seq for trial designs ----###

###--- trial design ---###

cs_consistant_td <- data.frame(
  applied_N = round(as.numeric(applied_N$year_4[1:40]), digits = 2),
  plot_id = as.character(seq(1,40, by = 1))
) %>% 
  left_join(., cs_consist_yield, by = c("applied_N", "plot_id"))


###---- Visualize the true yield responses and the estimated yield response from ofpe  ----###
ggplot()+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cs_consist_yield, size = 0.5)+
  geom_line(aes(x = applied_N, y = yield_max, group = plot_id), data = cs_consist_yield, size = 0.5)+
  # geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cs_consistant_td, color = "red")+
  # geom_smooth(aes(x = applied_N, y = yield_max), data = cs_consistant_td, color = "red")+
  theme_bw()


###--- make the figure to show that the levels change is the same as we expected ---###
# Convert plot_id to a factor and ensure levels are ordered numerically

ggplot() +
  geom_point(aes(x = applied_N, y = yield_max, color = plot_id), 
             data = cs_consist_yield, size = 0.5) +
  geom_line(aes(x = applied_N, y = yield_max, color = plot_id), 
            data = cs_consist_yield, size = 0.5) +
    scale_color_manual(
    name = "N level",  # Change legend title
    values = c("red", "orange", "green", "blue", "cyan", "purple", "pink"), # Adjust colors if needed
    labels = c("0", "50", "100", "150", "200", "250", "300")  # Change labels
  )+
  ylab("Yield (bu/ac)")+
  xlab("Applied N")+
  ggtitle("Yield response to N with corn-soy consistent trial design") +
  theme_bw()

```


```{r cache=TRUE}
###---- Find the uniform EONR  ----###

cs_consist_yield_analysis <- cs_consist_yield %>% 
  rowwise() %>% 
  data.table() %>% 
  .[, profit := yield_max*corn_price - applied_N*N_price] %>% 
  group_by(plot_id) %>%
  filter(profit == max(profit))

ggplot()+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cs_consist_yield, size = 0.5)+
  geom_line(aes(x = applied_N, y = yield_max, group = plot_id), data = cs_consist_yield, size = 0.5)+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cs_consistant_td, color = "blue")+
  geom_smooth(aes(x = applied_N, y = yield_max), data = cs_consistant_td, color = "blue")+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cs_consist_yield_analysis, color = "red")+
  theme_bw()

# site-specific EONRs statistic #
summary(cs_consist_yield_analysis$applied_N)

# Uniform EONR #

cs_consistent_uni <- cs_consist_yield %>% 
  data.table() %>% 
  .[, profit := yield_max*corn_price - applied_N*N_price] %>% 
  #---- find each level of N can bring how much profit for the whole field ----#
  .[, .(yield = mean(yield_max), profit = mean(profit)), by = applied_N] %>% 
  #---- filter out the uniform N that brings the highest profit ----#
  .[profit == max(profit), ] %>% 
  .[, type := "uniform N rate"]

cs_consistent_uni


## Estimate the EONR from OFPE ##

gam_re_cs <- gam(
  yield_max
  ~ s(applied_N),
  data = cs_consistant_td
)


eval_data_cs <- data.frame(
  applied_N = seq(
    0, 240, by = 5
  )
) %>% 
  data.table() %>% 
  .[, y_hat := predict(gam_re_cs, newdata = ., se = TRUE)]

cs_consistent_estimate <- eval_data_cs %>% 
  .[, profit := y_hat*corn_price - applied_N*N_price] %>% 
  filter(profit == max(profit)) %>% 
  .[, type := "ofpe estimated N rate"]


cs_consistent_estimate
  
```

```{r cache=TRUE}
# Compare the 3 types of EONRs together for cs ofpe in previous years

# site-specific EONRs statistic #
summary(cs_consist_yield_analysis$applied_N)
summary(cs_consist_yield_analysis$profit)

# Uniform EONR #
cs_consistent_uni

# Estimated EONR #
cs_consistent_estimate

```




# Eonomic analysis for corn-soy ofpe setting

```{r cache=TRUE}
###---- upload the simulation result ----###
cs_ofpe <- readRDS(here::here("Data", "Processed-Data", "corn_soy_ofpe_B105.rds"))

###---- find the simulated true yield response curves ----###

cs_ofpe_yield <- cs_ofpe %>% 
  mutate(CropYieldMaize = CropYieldMaize*10*0.0159/0.85) %>% 
  mutate(applied_N = applied_N*0.8921) %>% 
  mutate(applied_N = round(applied_N, digits = 2)) %>% 
  data.table() %>% 
  .[year == 2023, .(yield_max = max(CropYieldMaize)), by = .(applied_N, plot_id)]


###---- create N seq for trial designs ----###

cs_ofpe_td <- data.frame(
  applied_N = round(as.numeric(applied_N$year_9[1:100])*0.8921, digit = 2),
  plot_id = as.character(seq(1,100, by = 1))
) %>% 
  left_join(., cs_ofpe_yield, by = c("applied_N", "plot_id"))


###---- Visualize the true yield responses and the estimated yield response from ofpe  ----###
ggplot()+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cs_ofpe_yield, size = 0.5)+
  geom_line(aes(x = applied_N, y = yield_max, group = plot_id), data = cs_ofpe_yield, size = 0.5)+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cs_ofpe_td, color = "red")+
  geom_smooth(aes(x = applied_N, y = yield_max), data = cs_ofpe_td, color = "red")+
  xlab("N rate") +
  ylab("Yield") +
  ggtitle("yield response to N with corn-soy randomized trial design") +
  theme_bw()

```


```{r cache=TRUE}
###---- Find the uniform EONR  ----###

cs_ofpe_yield_analysis <- cs_ofpe_yield %>% 
  data.table() %>% 
  .[, profit := yield_max*corn_price - applied_N*N_price] %>% 
  group_by(plot_id) %>% 
  filter(profit == max(profit))


ggplot()+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cs_ofpe_yield, size = 0.5)+
  geom_line(aes(x = applied_N, y = yield_max, group = plot_id), data = cs_ofpe_yield, size = 0.5)+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cs_ofpe_td, color = "blue")+
  geom_smooth(aes(x = applied_N, y = yield_max), data = cs_ofpe_td, color = "blue")+
  geom_point(aes(x = applied_N, y = yield_max, group = plot_id), data = cs_ofpe_yield_analysis, color = "red")+
  theme_bw()

# site-specific EONRs statistic #
summary(cs_ofpe_yield_analysis$applied_N)

# Uniform EONR #

cs_ofpe_uni <- cs_ofpe_yield %>% 
  data.table() %>% 
  .[, profit := yield_max*corn_price - applied_N*N_price] %>% 
  #---- find each level of N can bring how much profit for the whole field ----#
  .[, .(yield = mean(yield_max), profit = mean(profit)), by = applied_N] %>% 
  #---- filter out the uniform N that brings the highest profit ----#
  .[profit == max(profit), ] %>% 
  .[, type := "uniform N rate"]

cs_ofpe_uni


## Estimate the EONR from OFPE ##

gam_re_cs <- gam(
  yield_max
  ~ s(applied_N),
  data = cs_ofpe_td
)


eval_data_cs <- data.frame(
  applied_N = seq(
    0, 240, by = 5
  )
) %>% 
  data.table() %>% 
  .[, y_hat := predict(gam_re_cs, newdata = ., se = TRUE)]

cs_ofpe_estimate <- eval_data_cs %>% 
  .[, profit := y_hat*corn_price - applied_N*N_price] %>% 
  filter(profit == max(profit)) %>% 
  .[, type := "ofpe estimated N rate"]
  
```

```{r cache=TRUE}
# Compare the 3 types of EONRs together for cs ofpe in previous years

# site-specific EONRs statistic #
summary(cs_ofpe_yield_analysis$applied_N)
summary(cs_ofpe_yield_analysis$profit)

# Uniform EONR #
cs_ofpe_uni

# Estimated EONR #
cs_ofpe_estimate

```


## No till ##

```{r}
###---- upload the simulation result ----###
cc_consist_notill <- readRDS(here::here("Data", "Processed-Data", "cc_consistent_B105_no_till.rds"))

###---- find the simulated true yield response curves ----###

cc_consist_notill_yield <- cc_consist_notill %>% 
  mutate(CropYield = CropYield*10*0.0159/0.85) %>% 
  mutate(applied_N = applied_N*0.8921) %>% 
  mutate(applied_N = round(applied_N, digits = 2)) %>% 
  data.table() %>% 
  .[year == 2023, .(yield_max = max(CropYield)), by = .(applied_N, plot_id)]


ggplot(cc_consist_notill_yield)+
  geom_point(aes(x = applied_N, y = yield_max, color = plot_id))+
  geom_point(aes(x = applied_N, y = yield_max, color = plot_id))+
  ggtitle("cc consistent trial design, normal weather, no tillage")



```






