---
title: "N leaching"
author: "Qianqian Du"
date: "2025-02-15"
output: html_document
---

# corn-corn consistent setting
```{r}

cc_consisten_b105 <- readRDS(here::here("Data", "Processed-Data", "cc_consistent_B105.rds"))


### Annual values ###
annual_cc_coon_leaching <- cc_consisten_b105 %>% 
  .[, .(annu_leach = max(AnnualNleaching)), .(year, plot_id)]

ggplot(data = annual_cc_coon_leaching)+
  geom_point(aes(x = year, y = annu_leach, color = plot_id))+
  geom_line(aes(x = year, y = annu_leach, color = plot_id))+
      scale_color_manual(
    name = "N level",  # Change legend title
    values = c("pink", "orange", "green", "blue", "cyan", "purple", "red"), # Adjust colors if needed
    labels = c("0", "50", "100", "150", "200", "250", "300")  # Change labels
  )


### Daily values ###

ggplot(data = cc_consisten_b105[year == 2016, ])+
  geom_point(aes(x = Date, y = AnnualNleaching, color = plot_id))+
  scale_color_manual(
    name = "N level",  # Change legend title
    values = c("pink", "orange", "green", "blue", "cyan", "purple", "red"), # Adjust colors if needed
    labels = c("0", "50", "100", "150", "200", "250", "300")  # Change labels
  )


ggplot(data = cc_consisten_b105)+
  geom_point(aes(x = Date, y = AnnualNleaching, color = plot_id))+
  facet_grid(.~ year)+
    scale_color_manual(
    name = "N level",  # Change legend title
    values = c("pink", "orange", "green", "blue", "cyan", "purple", "red"), # Adjust colors if needed
    labels = c("0", "50", "100", "150", "200", "250", "300")  # Change labels
  )


```


# corn-corn ofpe setting
```{r}

annual_cc_ofpe_leaching <- data.frame()

for (i in c("1", "2", "3", "4")) {
  
  cc_ofpe_b105 <- readRDS(here::here(paste0("Data/Processed-Data/Normal_till/cc_ofpe_B105_", i, ".rds")))
  
  ###--- Annual values ---###
  annual_cc_ofpe_leaching_i <- cc_ofpe_b105 %>% 
  .[, .(annu_leach = max(AnnualNleaching)), .(year, plot_id)]

  annual_cc_ofpe_leaching <- rbind(annual_cc_ofpe_leaching, annual_cc_ofpe_leaching_i)
  
}

ggplot(data = annual_cc_ofpe_leaching)+
  geom_point(aes(x = year, y = annu_leach, color = plot_id))+
  geom_line(aes(x = year, y = annu_leach, color = plot_id))


###--- find the distribution of N leaching in different N application levels ---###

annual_cc_ofpe_leaching$year <- as.character(annual_cc_ofpe_leaching$year)

ggplot(data = annual_cc_ofpe_leaching[year != 2014, ])+
  geom_boxplot(aes(x = year, y = annu_leach))+
  ggtitle("cc 2019 ofpe")


```

# corn-soy consistent setting
```{r}

cs_consistent_b105 <- readRDS(here::here("Data", "Processed-Data", "corn_soy_consistent_B105.rds"))

### Annual values ###
annual_cs_consis_leaching <- cs_consistent_b105 %>% 
  .[, .(annu_leach = max(AnnualNleaching)), .(year, plot_id)]

ggplot(data = annual_cs_consis_leaching)+
  geom_point(aes(x = year, y = annu_leach, color = plot_id))+
  geom_line(aes(x = year, y = annu_leach, color = plot_id))+
      scale_color_manual(
    name = "N level",  # Change legend title
    values = c("pink", "orange", "green", "blue", "cyan", "purple", "red"), # Adjust colors if needed
    labels = c("0", "50", "100", "150", "200", "250", "300")  # Change labels
  )


### Daily values ###

ggplot(data = cs_consistent_b105[year == 2019, ])+
  geom_point(aes(x = Date, y = AnnualNleaching, color = plot_id))+
    scale_color_manual(
    name = "N level",  # Change legend title
    values = c("pink", "orange", "green", "blue", "cyan", "purple", "red"), # Adjust colors if needed
    labels = c("0", "50", "100", "150", "200", "250", "300")  # Change labels
  )


ggplot(data = cs_consistent_b105)+
  geom_point(aes(x = Date, y = AnnualNleaching, color = plot_id))+
  facet_grid(.~ year)+
    geom_point(aes(x = Date, y = AnnualNleaching, color = plot_id))+
    scale_color_manual(
    name = "N level",  # Change legend title
    values = c("pink", "orange", "green", "blue", "cyan", "purple", "red"), # Adjust colors if needed
    labels = c("0", "50", "100", "150", "200", "250", "300")  # Change labels
  )

```


# corn-soy ofpe setting
```{r}

cs_ofpe_b105 <- readRDS(here::here("Data", "Processed-Data", "corn_soy_ofpe_B105_1.rds")) %>% 
  rbind(readRDS(here::here("Data", "Processed-Data", "corn_soy_ofpe_B105_2.rds"))) %>% 
  rbind(readRDS(here::here("Data", "Processed-Data", "corn_soy_ofpe_B105_3.rds"))) %>% 
  rbind(readRDS(here::here("Data", "Processed-Data", "corn_soy_ofpe_B105_4.rds")))

### Annual values ###
annual_cs_ofpe_leaching <- cs_ofpe_b105 %>% 
  .[, .(annu_leach = max(AnnualNleaching)), .(year, plot_id)]

ggplot(data = annual_cs_ofpe_leaching)+
  geom_point(aes(x = year, y = annu_leach, color = plot_id))+
  geom_line(aes(x = year, y = annu_leach, color = plot_id))



###--- find the distribution of N leaching in different N application levels ---###

annual_cs_ofpe_leaching$year <- as.character(annual_cs_ofpe_leaching$year)

ggplot(data = annual_cs_ofpe_leaching[year != c(2014, 2015), ])+
  geom_density(aes(annu_leach, fill = year, color = year), alpha = 0.1)


ggplot(data = annual_cs_ofpe_leaching[year != c(2014, 2015), ])+
  geom_histogram(aes(x = annu_leach))+
  facet_grid(year ~. )



### Daily values ###

ggplot(data = cs_ofpe_b105[year == 2023, ])+
  geom_point(aes(x = Date, y = AnnualNleaching, color = plot_id))


ggplot(data = cs_ofpe_b105)+
  geom_point(aes(x = Date, y = AnnualNleaching, color = plot_id))+
  facet_grid(.~ year)


annual_cs_ofpe_leaching <- data.frame()

for (i in c("1", "2", "3", "4")) {
  
  
  cs_ofpe_b105 <- readRDS(here::here(paste0("Data/Processed-Data/Normal_till/corn_soy_ofpe_B105_", i, ".rds")))
  
  ###--- Annual values ---###
  annual_cs_ofpe_leaching_i <- cs_ofpe_b105 %>% 
  .[, .(annu_leach = max(AnnualNleaching)), .(year, plot_id)]

  annual_cs_ofpe_leaching <- rbind(annual_cs_ofpe_leaching, annual_cs_ofpe_leaching_i)
  
}


###--- find the distribution of N leaching in different N application levels ---###

annual_cs_ofpe_leaching$year <- as.character(annual_cs_ofpe_leaching$year)

ggplot(data = annual_cs_ofpe_leaching[year != 2014, ])+
  geom_boxplot(aes(x = year, y = annu_leach))+
  ggtitle("cs 2019 ofpe")




```












